<?php
	$etype=get('etype');
	$excel='
	<p style="font-family:arial; font-size:18px;" align="left">
	<strong style="font-family:arial;">'.LANG_REPORT_TITLE.'</strong><br>'.LANG_REPORT_SUB_TITLE.'<br>
	<strong>'.LANG_REPORT_TABLE.'</strong> Mailingdatahealthsunidcards</p>';
	$excel.='
	<table border="1" cellspacing="0" style="font-family:arial; font-size:14px; width: 100%;" cellpadding="5">
    <tr>
	<td>FirstName</td>
	<td>'.$rows->firstName.'</td>
  	</tr>
    <tr>
	<td>LastName</td>
	<td>'.$rows->lastName.'</td>
  	</tr>
    <tr>
	<td>MiddleName</td>
	<td>'.$rows->middleName.'</td>
  	</tr>
    <tr>
	<td>FullName</td>
	<td>'.$rows->fullName.'</td>
  	</tr>
    <tr>
	<td>Address1</td>
	<td>'.$rows->address1.'</td>
  	</tr>
    <tr>
	<td>MmAddress1</td>
	<td>'.$rows->mmAddress1.'</td>
  	</tr>
    <tr>
	<td>Address2</td>
	<td>'.$rows->address2.'</td>
  	</tr>
    <tr>
	<td>MmAddress2</td>
	<td>'.$rows->mmAddress2.'</td>
  	</tr>
    <tr>
	<td>City</td>
	<td>'.$rows->city.'</td>
  	</tr>
    <tr>
	<td>MmCity</td>
	<td>'.$rows->mmCity.'</td>
  	</tr>
    <tr>
	<td>State</td>
	<td>'.$rows->state.'</td>
  	</tr>
    <tr>
	<td>MmState</td>
	<td>'.$rows->mmState.'</td>
  	</tr>
    <tr>
	<td>ZipCode</td>
	<td>'.$rows->zipCode.'</td>
  	</tr>
    <tr>
	<td>MmZipCode</td>
	<td>'.$rows->mmZipCode.'</td>
  	</tr>
    <tr>
	<td>Country</td>
	<td>'.$rows->country.'</td>
  	</tr>
    <tr>
	<td>MmCountry</td>
	<td>'.$rows->mmCountry.'</td>
  	</tr>
    <tr>
	<td>MmImb</td>
	<td>'.$rows->mmImb.'</td>
  	</tr>
    <tr>
	<td>MmOpt</td>
	<td>'.$rows->mmOpt.'</td>
  	</tr>
    <tr>
	<td>MmReturnCode</td>
	<td>'.$rows->mmReturnCode.'</td>
  	</tr>
    <tr>
	<td>MmDpv</td>
	<td>'.$rows->mmDpv.'</td>
  	</tr>
    <tr>
	<td>MmOrder</td>
	<td>'.$rows->mmOrder.'</td>
  	</tr>
    <tr>
	<td>PdfLocation</td>
	<td>'.$rows->pdfLocation.'</td>
  	</tr>
    <tr>
	<td>PdfTotPages</td>
	<td>'.$rows->pdfTotPages.'</td>
  	</tr>
    <tr>
	<td>MemberPBPID</td>
	<td>'.$rows->memberPBPID.'</td>
  	</tr>
    <tr>
	<td>CreatedDate</td>
	<td>'.$rows->createdDate.'</td>
  	</tr>
    <tr>
	<td>ExportedDate</td>
	<td>'.$rows->exportedDate.'</td>
  	</tr>
    <tr>
	<td>PostmarkedDate</td>
	<td>'.$rows->postmarkedDate.'</td>
  	</tr>
    <tr>
	<td>MemberNumber</td>
	<td>'.$rows->memberNumber.'</td>
  	</tr>
    <tr>
	<td>EffectiveDate</td>
	<td>'.$rows->effectiveDate.'</td>
  	</tr>
    <tr>
	<td>DateOfBirth</td>
	<td>'.$rows->dateOfBirth.'</td>
  	</tr>
    <tr>
	<td>CityStateZIP</td>
	<td>'.$rows->cityStateZIP.'</td>
  	</tr>
    <tr>
	<td>County</td>
	<td>'.$rows->county.'</td>
  	</tr>
    <tr>
	<td>HomePhone</td>
	<td>'.$rows->homePhone.'</td>
  	</tr>
    <tr>
	<td>RxGroup</td>
	<td>'.$rows->rxGroup.'</td>
  	</tr>
    <tr>
	<td>CoverageType</td>
	<td>'.$rows->coverageType.'</td>
  	</tr>
    <tr>
	<td>OfficeVisitCoPay</td>
	<td>'.$rows->officeVisitCoPay.'</td>
  	</tr>
    <tr>
	<td>ERCoPay</td>
	<td>'.$rows->eRCoPay.'</td>
  	</tr>
    <tr>
	<td>MemberServicesPhone</td>
	<td>'.$rows->memberServicesPhone.'</td>
  	</tr>
    <tr>
	<td>TTYPhone</td>
	<td>'.$rows->tTYPhone.'</td>
  	</tr>
    <tr>
	<td>CarrierNumber</td>
	<td>'.$rows->carrierNumber.'</td>
  	</tr>
    <tr>
	<td>PlanName</td>
	<td>'.$rows->planName.'</td>
  	</tr>
    <tr>
	<td>PBPNumber</td>
	<td>'.$rows->pBPNumber.'</td>
  	</tr>
    <tr>
	<td>ProviderName</td>
	<td>'.$rows->providerName.'</td>
  	</tr>
    <tr>
	<td>ProviderNumber</td>
	<td>'.$rows->providerNumber.'</td>
  	</tr>
    <tr>
	<td>ProviderPhone</td>
	<td>'.$rows->providerPhone.'</td>
  	</tr>
    <tr>
	<td>DefaultLanguage</td>
	<td>'.$rows->defaultLanguage.'</td>
  	</tr>
    <tr>
	<td>ErrorCode</td>
	<td>'.$rows->errorCode.'</td>
  	</tr>
    <tr>
	<td>ErrorDescription</td>
	<td>'.$rows->errorDescription.'</td>
  	</tr>
    <tr>
	<td>MailingDataFile Id</td>
	<td>'.$rows->mailingDataFile_id.'</td>
  	</tr>
    <tr>
	<td>MailingPrintReadyFile Id</td>
	<td>'.$rows->mailingPrintReadyFile_id.'</td>
  	</tr>
    <tr>
	<td>MmCOAMoveToDate</td>
	<td>'.$rows->mmCOAMoveToDate.'</td>
  	</tr>
    <tr>
	<td>MmCOAMoveType</td>
	<td>'.$rows->mmCOAMoveType.'</td>
  	</tr>
    <tr>
	<td>Generic1</td>
	<td>'.$rows->generic1.'</td>
  	</tr>
    <tr>
	<td>Generic2</td>
	<td>'.$rows->generic2.'</td>
  	</tr>
    <tr>
	<td>MmImbDigi</td>
	<td>'.$rows->mmImbDigi.'</td>
  	</tr>';
   $excel.='</table>';
	
	$filename1= 'mailingdatahealthsunidcards_'.date('Y-m-d').'.doc';
	$filename2= 'mailingdatahealthsunidcards_'.date('Y-m-d').'.xls';
	$pdf_output= 'mailingdatahealthsunidcards_'.date('Y-m-d').'.pdf';
	if ($etype == 'word') 
    {
        MSWord($filename1);
        print $excel;
    }
    elseif ($etype == 'excel') 
    {
        MSExcell($filename2);
        print $excel;
    }
    elseif ($etype == 'printer') 
    {
        HTSPrint();
        print $excel;
    }
    elseif ($etype == 'PDF') 
    {
        HezecomPDF($pdf_output,$excel,1);
        print $excel;
    }
    ?>
    